In [4]:
def fn(a, b, /, c):
    pass

In [91]:
class c:
    def fn():
        pass

In [102]:
obj = c()
obj.fn.__func__

<function __main__.c.fn()>

In [103]:
obj.fn

<bound method c.fn of <__main__.c object at 0x000001BA19E6B130>>

In [106]:
obj.fn is obj.fn.__func__

False

In [47]:
0 or []

[]

In [45]:
0 and 0

0

In [7]:
fn(c=1, 1, 2)

SyntaxError: positional argument follows keyword argument (DELLTE~1/ipykernel_13164/3486495555.py, line 1)

In [86]:
def fn():
    pass

In [89]:
type(fn)

function

In [78]:
def fn(b):pass

In [79]:
hash(fn)

118675625436

In [83]:
hash('a')

-943405411007546959

In [85]:
hash(-943405411007546959) == hash('a')

True

In [129]:
asdf=1
def fn():
    global asdf
    print(dir())
fn()

[]


In [130]:
iter([1, 2, 3, 5])

In [1]:
import numpy as np

In [5]:
ls = [1, 2, ['a', 'b'], 3, 4]
ls[2, 0]

TypeError: list indices must be integers or slices, not tuple

In [27]:
string = '0123456'
string[-1:0:-1]

'654321'

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])

In [4]:
arr.shape = (2,3)

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr = np.array([1,2,3,4,5,6])

In [8]:
arr2 = np.reshape(arr, (2,3))

In [9]:
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr[0] = 99

In [12]:
arr

array([99,  2,  3,  4,  5,  6])

In [13]:
arr2

array([[99,  2,  3],
       [ 4,  5,  6]])

In [14]:
arr  = np.array([1,2,3,4,5,6])

In [16]:
arr2 = np.resize(arr, (2,3))

In [17]:
arr[0]=99

In [18]:
arr

array([99,  2,  3,  4,  5,  6])

In [19]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr = np.array([1,2,3,4,5,6])

In [25]:
arr.resize((2,2))

In [26]:
arr

array([[1, 2],
       [3, 4]])

In [27]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [30]:
np.transpose(arr)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.transpose([
    [
        [1,2],
        [4,5]
    ],
    [
        [6,7],
        [8,9]
    ]
])

In [42]:
np.transpose?

Signature: np.transpose(a, axes=None)
Docstring:
Reverse or permute the axes of an array; returns the modified array.

For an array a with two axes, transpose(a) gives the matrix transpose.

Parameters
----------
a : array_like
    Input array.
axes : tuple or list of ints, optional
    If specified, it must be a tuple or list which contains a permutation of
    [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
    returned array will correspond to the axis numbered ``axes[i]`` of the
    input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
    reverses the order of the axes.

Returns
-------
p : ndarray
    `a` with its axes permuted.  A view is returned whenever
    possible.

See Also
--------
moveaxis
argsort

Notes
-----
Use `transpose(a, argsort(axes))` to invert the transposition of tensors
when using the `axes` keyword argument.

Transposing a 1-D array returns an unchanged view of the original array.

Examples
--------
>>> x = np.arange(4).

In [ ]:
np.ndarray.transpose?

In [66]:
arr = np.array([[1,2,3]])

In [67]:
arr2 = np.transpose(arr)

In [68]:
arr[0]=99

In [69]:
arr

array([[99, 99, 99]])

In [70]:
arr2

array([[99],
       [99],
       [99]])

In [43]:
arr2.T

array([99,  2,  3])

In [46]:
np.swapaxes([[1],[2]], 0, 1)

array([[1, 2]])

In [51]:
np.swapaxes([
    [
        [5,4],
        [3,2]
    ],
    [
        [6,7],
        [8,9]
    ]
], 2,1)

array([[[5, 3],
        [4, 2]],

       [[6, 8],
        [7, 9]]])

In [53]:
arr = np.array([
    [
        [5,4],
        [3,2]
    ],
    [
        [6,7],
        [8,9]
    ]
])

In [54]:
arr2 = np.swapaxes(arr, 0, 1)

In [55]:
arr[0,0,0] = 99

In [56]:
arr

array([[[99,  4],
        [ 3,  2]],

       [[ 6,  7],
        [ 8,  9]]])

In [57]:
arr2

array([[[99,  4],
        [ 6,  7]],

       [[ 3,  2],
        [ 8,  9]]])

In [ ]:
np.append?

In [ ]:
np.insert?

In [ ]:
np.delete?

In [ ]:
np.sort?

In [75]:
arr = np.array([0,2,3,1])

In [76]:
arr2 = np.sort(arr)

In [77]:
arr[0] = 99

In [78]:
arr

array([99,  2,  3,  1])

In [79]:
arr2

array([0, 1, 2, 3])

In [ ]:
np.concatenate?

In [94]:
np.concatenate((
    np.random.random((2)),
    np.arange(3)
), axis=0)

array([0.81356375, 0.56762745, 0.        , 1.        , 2.        ])

In [103]:
np.concatenate((
    np.random.random((2,2)),
    np.arange(6).reshape((2,3))
), axis=1)

array([[0.55323835, 0.1487693 , 0.        , 1.        , 2.        ],
       [0.51844455, 0.74419338, 3.        , 4.        , 5.        ]])

In [110]:
np.concatenate((
    np.full((2,2,2),99),
    np.arange(12).reshape((2,2,3))
), axis=2)

array([[[99, 99,  0,  1,  2],
        [99, 99,  3,  4,  5]],

       [[99, 99,  6,  7,  8],
        [99, 99,  9, 10, 11]]])

In [1]:
import pandas as pd

In [6]:
s = pd.Series([1,2,3,4,5], index=range(10,0,-2))
s

10    1
8     2
6     3
4     4
2     5
dtype: int64

In [7]:
s.index

RangeIndex(start=10, stop=0, step=-2)

In [26]:
# s = pd.Series([10,11,21,31,41], index=[(1,),(2,),(3,),(4,),(5,)])
s = pd.Series([10,11,21,31,41], index=[0.1, 0.2, 0.3, 0.4, 0.5])
s

0.1    10
0.2    11
0.3    21
0.4    31
0.5    41
dtype: int64

In [29]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([1,2,3,4])

In [30]:
s1+s2

0    2
1    4
2    6
3    8
dtype: int64

In [35]:
s1 = pd.Series([1,2,3,4], index=[1,2,3,4])
s2 = pd.Series([1,2,3,4], index=[4,3,2,1])
s1+s2

1    5
2    5
3    5
4    5
dtype: int64

In [36]:
s1 = pd.Series([1,2,3,4], index=[0,1,4,9])
s2 = pd.Series([1,2,3,4], index=[0,1,7,1])
s1 + s2

0    2.0
1    4.0
1    6.0
4    NaN
7    NaN
9    NaN
dtype: float64

In [37]:
s1 = pd.Series([1,2,3,4], index=[1,2,3,4])
s2 = pd.Series([1,2,3,4], index=[4,3,2,1])

In [38]:
s1.add(s2)

1    5
2    5
3    5
4    5
dtype: int64

In [39]:
s1

1    1
2    2
3    3
4    4
dtype: int64

In [40]:
s2

4    1
3    2
2    3
1    4
dtype: int64

In [45]:
s1 = pd.Series([1,2,3,4], index=[0,1,4,9])
s2 = pd.Series([1,2,3,4], index=[0,1,7,1])
s1.add(s2, fill_value=0)

0    2.0
1    4.0
1    6.0
4    3.0
7    3.0
9    4.0
dtype: float64

In [ ]:
pd.Series.add?

In [49]:
s = pd.Series([1,2,3,4,5,6])

In [51]:
s[[True, True, False, False, False, False]]

0    1
1    2
dtype: int64

In [52]:
s[s>3]

3    4
4    5
5    6
dtype: int64

In [1]:
1&3

1

In [2]:
min([1,2,4,'abc'])

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
import pandas as pd

In [ ]:
pd.Data