In [4]:
def fn(a, b, /, c):
    pass

In [91]:
class c:
    def fn():
        pass

In [102]:
obj = c()
obj.fn.__func__

<function __main__.c.fn()>

In [103]:
obj.fn

<bound method c.fn of <__main__.c object at 0x000001BA19E6B130>>

In [106]:
obj.fn is obj.fn.__func__

False

In [47]:
0 or []

[]

In [45]:
0 and 0

0

In [7]:
fn(c=1, 1, 2)

SyntaxError: positional argument follows keyword argument (DELLTE~1/ipykernel_13164/3486495555.py, line 1)

In [86]:
def fn():
    pass

In [89]:
type(fn)

function

In [78]:
def fn(b):pass

In [79]:
hash(fn)

118675625436

In [83]:
hash('a')

-943405411007546959

In [85]:
hash(-943405411007546959) == hash('a')

True

In [129]:
asdf=1
def fn():
    global asdf
    print(dir())
fn()

[]


In [130]:
iter([1, 2, 3, 5])

In [1]:
import numpy as np

In [5]:
ls = [1, 2, ['a', 'b'], 3, 4]
ls[2, 0]

TypeError: list indices must be integers or slices, not tuple

In [27]:
string = '0123456'
string[-1:0:-1]

'654321'

In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6])

In [4]:
arr.shape = (2,3)

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr = np.array([1,2,3,4,5,6])

In [8]:
arr2 = np.reshape(arr, (2,3))

In [9]:
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr[0] = 99

In [12]:
arr

array([99,  2,  3,  4,  5,  6])

In [13]:
arr2

array([[99,  2,  3],
       [ 4,  5,  6]])

In [14]:
arr  = np.array([1,2,3,4,5,6])

In [16]:
arr2 = np.resize(arr, (2,3))

In [17]:
arr[0]=99

In [18]:
arr

array([99,  2,  3,  4,  5,  6])

In [19]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr = np.array([1,2,3,4,5,6])

In [25]:
arr.resize((2,2))

In [26]:
arr

array([[1, 2],
       [3, 4]])

In [27]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [30]:
np.transpose(arr)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.transpose([
    [
        [1,2],
        [4,5]
    ],
    [
        [6,7],
        [8,9]
    ]
])

In [42]:
np.transpose?

Signature: np.transpose(a, axes=None)
Docstring:
Reverse or permute the axes of an array; returns the modified array.

For an array a with two axes, transpose(a) gives the matrix transpose.

Parameters
----------
a : array_like
    Input array.
axes : tuple or list of ints, optional
    If specified, it must be a tuple or list which contains a permutation of
    [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
    returned array will correspond to the axis numbered ``axes[i]`` of the
    input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
    reverses the order of the axes.

Returns
-------
p : ndarray
    `a` with its axes permuted.  A view is returned whenever
    possible.

See Also
--------
moveaxis
argsort

Notes
-----
Use `transpose(a, argsort(axes))` to invert the transposition of tensors
when using the `axes` keyword argument.

Transposing a 1-D array returns an unchanged view of the original array.

Examples
--------
>>> x = np.arange(4).

In [ ]:
np.ndarray.transpose?

In [66]:
arr = np.array([[1,2,3]])

In [67]:
arr2 = np.transpose(arr)

In [68]:
arr[0]=99

In [69]:
arr

array([[99, 99, 99]])

In [70]:
arr2

array([[99],
       [99],
       [99]])

In [43]:
arr2.T

array([99,  2,  3])

In [46]:
np.swapaxes([[1],[2]], 0, 1)

array([[1, 2]])

In [51]:
np.swapaxes([
    [
        [5,4],
        [3,2]
    ],
    [
        [6,7],
        [8,9]
    ]
], 2,1)

array([[[5, 3],
        [4, 2]],

       [[6, 8],
        [7, 9]]])

In [53]:
arr = np.array([
    [
        [5,4],
        [3,2]
    ],
    [
        [6,7],
        [8,9]
    ]
])

In [54]:
arr2 = np.swapaxes(arr, 0, 1)

In [55]:
arr[0,0,0] = 99

In [56]:
arr

array([[[99,  4],
        [ 3,  2]],

       [[ 6,  7],
        [ 8,  9]]])

In [57]:
arr2

array([[[99,  4],
        [ 6,  7]],

       [[ 3,  2],
        [ 8,  9]]])

In [ ]:
np.append?

In [ ]:
np.insert?

In [ ]:
np.delete?

In [ ]:
np.sort?

In [75]:
arr = np.array([0,2,3,1])

In [76]:
arr2 = np.sort(arr)

In [77]:
arr[0] = 99

In [78]:
arr

array([99,  2,  3,  1])

In [79]:
arr2

array([0, 1, 2, 3])

In [ ]:
np.concatenate?

In [94]:
np.concatenate((
    np.random.random((2)),
    np.arange(3)
), axis=0)

array([0.81356375, 0.56762745, 0.        , 1.        , 2.        ])

In [103]:
np.concatenate((
    np.random.random((2,2)),
    np.arange(6).reshape((2,3))
), axis=1)

array([[0.55323835, 0.1487693 , 0.        , 1.        , 2.        ],
       [0.51844455, 0.74419338, 3.        , 4.        , 5.        ]])

In [110]:
np.concatenate((
    np.full((2,2,2),99),
    np.arange(12).reshape((2,2,3))
), axis=2)

array([[[99, 99,  0,  1,  2],
        [99, 99,  3,  4,  5]],

       [[99, 99,  6,  7,  8],
        [99, 99,  9, 10, 11]]])

In [1]:
import pandas as pd

In [6]:
s = pd.Series([1,2,3,4,5], index=range(10,0,-2))
s

10    1
8     2
6     3
4     4
2     5
dtype: int64

In [7]:
s.index

RangeIndex(start=10, stop=0, step=-2)

In [26]:
# s = pd.Series([10,11,21,31,41], index=[(1,),(2,),(3,),(4,),(5,)])
s = pd.Series([10,11,21,31,41], index=[0.1, 0.2, 0.3, 0.4, 0.5])
s

0.1    10
0.2    11
0.3    21
0.4    31
0.5    41
dtype: int64

In [29]:
s1 = pd.Series([1,2,3,4])
s2 = pd.Series([1,2,3,4])

In [30]:
s1+s2

0    2
1    4
2    6
3    8
dtype: int64

In [35]:
s1 = pd.Series([1,2,3,4], index=[1,2,3,4])
s2 = pd.Series([1,2,3,4], index=[4,3,2,1])
s1+s2

1    5
2    5
3    5
4    5
dtype: int64

In [36]:
s1 = pd.Series([1,2,3,4], index=[0,1,4,9])
s2 = pd.Series([1,2,3,4], index=[0,1,7,1])
s1 + s2

0    2.0
1    4.0
1    6.0
4    NaN
7    NaN
9    NaN
dtype: float64

In [37]:
s1 = pd.Series([1,2,3,4], index=[1,2,3,4])
s2 = pd.Series([1,2,3,4], index=[4,3,2,1])

In [38]:
s1.add(s2)

1    5
2    5
3    5
4    5
dtype: int64

In [39]:
s1

1    1
2    2
3    3
4    4
dtype: int64

In [40]:
s2

4    1
3    2
2    3
1    4
dtype: int64

In [45]:
s1 = pd.Series([1,2,3,4], index=[0,1,4,9])
s2 = pd.Series([1,2,3,4], index=[0,1,7,1])
s1.add(s2, fill_value=0)

0    2.0
1    4.0
1    6.0
4    3.0
7    3.0
9    4.0
dtype: float64

In [ ]:
pd.Series.add?

In [49]:
s = pd.Series([1,2,3,4,5,6])

In [51]:
s[[True, True, False, False, False, False]]

0    1
1    2
dtype: int64

In [52]:
s[s>3]

3    4
4    5
5    6
dtype: int64

In [1]:
1&3

1

In [2]:
min([1,2,4,'abc'])

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
import pandas as pd

In [ ]:
pd.Data

In [1]:
import numpy as np

In [5]:
np.min([[1,2,],[3,4]],axis=1)

array([1, 3])

In [6]:
np.prod?

Signature:
np.prod(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    initial=<no value>,
    where=<no value>,
)
Docstring:
Return the product of array elements over a given axis.

Parameters
----------
a : array_like
    Input data.
axis : None or int or tuple of ints, optional
    Axis or axes along which a product is performed.  The default,
    axis=None, will calculate the product of all the elements in the
    input array. If axis is negative it counts from the last to the
    first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a product is performed on all of the
    axes specified in the tuple instead of a single axis or all the
    axes as before.
dtype : dtype, optional
    The type of the returned array, as well as of the accumulator in
    which the elements are multiplied.  The dtype of `a` is used by
    default unless `a` has an integer dtype of less precision than the
    default platform integer.  In that case, if `

In [ ]:
arr = np.random.randint(1, (3,3))


array([[8, 7, 8],
       [4, 4, 3],
       [2, 4, 2]])

In [17]:
rows=[True, False, True]
col=[True, False, False]

arr[rows,col]

array([8, 2])

In [19]:
np.array([1,2,3]).transpose()

array([1, 2, 3])

In [20]:
np.array([[1],[2],[3]]).transpose()

array([[1, 2, 3]])

In [21]:
np.append?

Signature: np.append(arr, values, axis=None)
Docstring:
Append values to the end of an array.

Parameters
----------
arr : array_like
    Values are appended to a copy of this array.
values : array_like
    These values are appended to a copy of `arr`.  It must be of the
    correct shape (the same shape as `arr`, excluding `axis`).  If
    `axis` is not specified, `values` can be any shape and will be
    flattened before use.
axis : int, optional
    The axis along which `values` are appended.  If `axis` is not
    given, both `arr` and `values` are flattened before use.

Returns
-------
append : ndarray
    A copy of `arr` with `values` appended to `axis`.  Note that
    `append` does not occur in-place: a new array is allocated and
    filled.  If `axis` is None, `out` is a flattened array.

See Also
--------
insert : Insert elements into an array.
delete : Delete elements from an array.

Examples
--------
>>> np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
array([1, 2, 3, ..., 7, 8, 

In [27]:
arr = np.random.randint(0, 10, (5,5))
arr

array([[4, 2, 2, 9, 6],
       [0, 3, 7, 5, 1],
       [6, 3, 2, 5, 1],
       [9, 0, 1, 4, 5],
       [0, 0, 5, 1, 2]])

In [31]:
arr[1:2,:]

array([[0, 3, 7, 5, 1]])

In [ ]:
np.matmul?

In [33]:
import pandas as pd
import numpy as np

In [34]:
s = pd.Series([1,2,3,4,5], index=[1,2,2,3,4])
s

1    1
2    2
2    3
3    4
4    5
dtype: int64

In [36]:
s[2]

2    2
2    3
dtype: int64

In [37]:
s = pd.Series([1,2,3,4,5,5,6,7])

In [43]:
pd.Series(map(lambda v: v**2, s))

0     1
1     4
2     9
3    16
4    25
5    25
6    36
7    49
dtype: int64

In [57]:
s.map(lambda v: v**2)

0     1
1     4
2     9
3    16
4    25
5    25
6    36
7    49
dtype: int64

In [55]:
df = pd.DataFrame([['z', 'y', 'x', 'f', 'h'], ['a', 'b', 'c', 'd', 'e']])
df

0  1  2  3  4
0  z  y  x  f  h
1  a  b  c  d  e

In [56]:
pd.DataFrame(map(lambda x: print(x), df))

0
1
2
3
4


0
0  None
1  None
2  None
3  None
4  None

In [ ]:
df.replace?

In [ ]:
s.replace?

In [ ]:
df.apply?

In [ ]:
s.apply?

In [67]:
s.apply(lambda x: print(x))

1
2
3
4
5
5
6
7


0    None
1    None
2    None
3    None
4    None
5    None
6    None
7    None
dtype: object

In [69]:
df

0  1  2  3  4
0  z  y  x  f  h
1  a  b  c  d  e

In [70]:
df.apply(lambda x: print(x), axis=1)

0    z
1    y
2    x
3    f
4    h
Name: 0, dtype: object
0    a
1    b
2    c
3    d
4    e
Name: 1, dtype: object


0    None
1    None
dtype: object

In [ ]:
s.add?

In [ ]:
df.add?

In [ ]:
s.subtract?

In [ ]:
s.mul?

In [ ]:
s.divide?

In [ ]:
s.drop?

In [ ]:
df.drop?

In [ ]:
df.append?

In [ ]:
df.dropna?

In [ ]:
pd.get_dummies?

In [ ]:
df.groupby?

In [86]:
df = pd.read_csv('datasets/groupbydata1.csv')
df

date     city  temperature
0   01/01/2022   lahore            8
1   02/01/2022   lahore           10
2   03/01/2022   lahore            5
3   04/01/2022   lahore            6
4   05/01/2022   lahore           12
5   01/01/2022  karachi           18
6   02/01/2022  karachi           10
7   03/01/2022  karachi           12
8   04/01/2022  karachi           15
9   05/01/2022  karachi           16
10  01/01/2022   murree           -5
11  02/01/2022   murree           -3
12  03/01/2022   murree           -4
13  04/01/2022   murree           -1
14  05/01/2022   murree           -7

In [92]:
df.groupby('city').temperature.get_group('lahore')

0     8
1    10
2     5
3     6
4    12
Name: temperature, dtype: int64

In [93]:
df = pd.read_csv('datasets/so_survey_subset.csv', index_col='Respondent')
df

MainBranch Hobbyist  \
Respondent                                                               
1                      I am a student who is learning to code      Yes   
2                      I am a student who is learning to code       No   
3           I am not primarily a developer, but I write co...      Yes   
4                              I am a developer by profession       No   
5                              I am a developer by profession      Yes   
...                                                       ...      ...   
88377                                                     NaN      Yes   
88601                                                     NaN       No   
88802                                                     NaN       No   
88816                                                     NaN       No   
88863                                                     NaN      Yes   

                           Country YearsCode  ConvertedComp  \
Respondent                                                    
1                   United Kingdom         4            NaN   
2           Bosnia and Herzegovina       NaN            NaN   
3                         Thailand         3         8820.0   
4                    United States         3        61000.0   
5                          Ukraine        16            NaN   
...                            ...       ...            ...   
88377                       Canada       NaN            NaN   
88601                          NaN       NaN            NaN   
88802                          NaN       NaN            NaN   
88816                          NaN       NaN            NaN   
88863                        Spain         8            NaN   

                                           LanguageWorkedWith SocialMedia  \
Respondent                                                                  
1                             HTML/CSS;Java;JavaScript;Python     Twitter   
2                                         C++;HTML/CSS;Python   Instagram   
3                                                    HTML/CSS      Reddit   
4                                         C;C++;C#;Python;SQL      Reddit   
5                 C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA    Facebook   
...                                                       ...         ...   
88377                           HTML/CSS;JavaScript;Other(s):     YouTube   
88601                                                     NaN         NaN   
88802                                                     NaN         NaN   
88816                                                     NaN         NaN   
88863       Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...    WhatsApp   

             Age Gender  
Respondent               
1           14.0    Man  
2           19.0    Man  
3           28.0    Man  
4           22.0    Man  
5           30.0    Man  
...          ...    ...  
88377        NaN    Man  
88601        NaN    NaN  
88802        NaN    NaN  
88816        NaN    NaN  
88863       18.0    Man  

[88883 rows x 9 columns]

In [99]:
df[df.Country == 'Pakistan'].SocialMedia.value_counts().index[0]

'WhatsApp'

In [116]:
(df[['Country', 'SocialMedia']].groupby('Country').value_counts())

Country      SocialMedia             
Afghanistan  Facebook                    15
             YouTube                      9
             I don't use social media     6
             WhatsApp                     4
             Instagram                    1
                                         ..
Zimbabwe     Facebook                     3
             YouTube                      3
             LinkedIn                     2
             Instagram                    2
             Reddit                       1
Length: 1220, dtype: int64

In [118]:
df[['Country', 'SocialMedia']]

Country SocialMedia
Respondent                                    
1                   United Kingdom     Twitter
2           Bosnia and Herzegovina   Instagram
3                         Thailand      Reddit
4                    United States      Reddit
5                          Ukraine    Facebook
...                            ...         ...
88377                       Canada     YouTube
88601                          NaN         NaN
88802                          NaN         NaN
88816                          NaN         NaN
88863                        Spain    WhatsApp

[88883 rows x 2 columns]

In [ ]:
df.groupby('Country').apply(lambda x: print(x['LanguageWorkedWith'].shape))

In [133]:
import pandas as pd

In [ ]:
pd.merge?

In [ ]:
pd.concat?

In [ ]:
df.append?