In [1]:
import numpy as np

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.array([1, 2, 3], order='F').strides

(4,)

In [14]:
np.array([1, 2, 3], order='C').strides

(4,)

In [22]:
np.array([[1, 2]], order='C', dtype=np.uint8).strides

(2, 1)

In [23]:
np.array([[1, 2]], order='F', dtype=np.uint8).strides

(1, 1)

In [18]:
np.array([[1, 2]], order='C').dtype

dtype('int32')

In [19]:
np.array([[1, 2]], order='F').dtype

dtype('int32')

In [33]:
arr = np.array([[1, 2, 3, 4, 5]])

In [59]:
print('arr: ', arr)
print('rank: ', arr.ndim)
print('shape: ', arr.shape)
print('strides: ', arr.strides)
print('itemsize: ', arr.itemsize)
print('nbytes: ', arr.nbytes)

arr:  1
rank:  0
shape:  ()
strides:  ()
itemsize:  4
nbytes:  4


In [37]:
arr.data

In [43]:
arr.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [45]:
np.array([1, 2], order='c').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [48]:
np.array([1, 2], order='f').flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [51]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [56]:
np.int8?

Init signature: np.int8(self, /, *args, **kwargs)
Docstring:     
Signed integer type, compatible with C ``char``.

:Character code: ``'b'``
:Canonical name: `numpy.byte`
:Alias on this platform: `numpy.int8`: 8-bit signed integer (``-128`` to ``127``).
File:           c:\programdata\anaconda3\envs\tools-and-techniques-in-data-science\lib\site-packages\numpy\__init__.py
Type:           type
Subclasses:     


# 0 D

In [68]:
arr = np.array(1)

In [69]:
print('arr: ', arr)
print('ndim: ', arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('itemsize: ', arr.itemsize)
print('dtype: ', arr.dtype)
print('nbytes: ', arr.nbytes)
print('strides: ', arr.strides)

arr:  1
ndim:  0
shape:  ()
size:  1
itemsize:  4
dtype:  int32
nbytes:  4
strides:  ()


# 1 D

In [71]:
arr = np.array([1, 2, 3, 4])

In [72]:
print('arr: ', arr)
print('ndim: ', arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('itemsize: ', arr.itemsize)
print('dtype: ', arr.dtype)
print('nbytes: ', arr.nbytes)
print('strides: ', arr.strides)

arr:  [1 2 3 4]
ndim:  1
shape:  (4,)
size:  4
itemsize:  4
dtype:  int32
nbytes:  16
strides:  (4,)


# 2 D

In [73]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [74]:
print('arr: ', arr)
print('ndim: ', arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('itemsize: ', arr.itemsize)
print('dtype: ', arr.dtype)
print('nbytes: ', arr.nbytes)
print('strides: ', arr.strides)

arr:  [[1 2 3]
 [4 5 6]]
ndim:  2
shape:  (2, 3)
size:  6
itemsize:  4
dtype:  int32
nbytes:  24
strides:  (12, 4)


In [75]:
arr = np.array([[1], [2], [3]])

In [76]:
print('arr: ', arr)
print('ndim: ', arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('itemsize: ', arr.itemsize)
print('dtype: ', arr.dtype)
print('nbytes: ', arr.nbytes)
print('strides: ', arr.strides)

arr:  [[1]
 [2]
 [3]]
ndim:  2
shape:  (3, 1)
size:  3
itemsize:  4
dtype:  int32
nbytes:  12
strides:  (4, 4)


In [77]:
arr = np.array([[1, 2, 3]])

In [78]:
print('arr: ', arr)
print('ndim: ', arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('itemsize: ', arr.itemsize)
print('dtype: ', arr.dtype)
print('nbytes: ', arr.nbytes)
print('strides: ', arr.strides)

arr:  [[1 2 3]]
ndim:  2
shape:  (1, 3)
size:  3
itemsize:  4
dtype:  int32
nbytes:  12
strides:  (12, 4)


# 3 D

In [82]:
arr = np.array([
    [[1, 2, 3], [4, 5, 6]]
])

In [84]:
print('arr: ', arr)
print('ndim: ', arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('itemsize: ', arr.itemsize)
print('dtype: ', arr.dtype)
print('nbytes: ', arr.nbytes)
print('strides: ', arr.strides)

arr:  [[[1 2 3]
  [4 5 6]]]
ndim:  3
shape:  (1, 2, 3)
size:  6
itemsize:  4
dtype:  int32
nbytes:  24
strides:  (24, 12, 4)


In [ ]:
help(np.zeros)

In [ ]:
np.empty?

In [113]:
np.empty_like

<function numpy.empty_like>

In [114]:
np.zeros_like

<function numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)>

In [115]:
np.ones_like

<function numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)>

In [122]:
np.fromstring('[1,2,3]', sep=',')

F:\else\Windows\DELLTE~1/ipykernel_15996/2359113920.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('[1,2,3]', sep=',')


array([], dtype=float64)

In [123]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [125]:
np.arange(1, 3)

array([1, 2])

In [126]:
np.arange(1, 5, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [127]:
np.arange(10, 3, -1)

array([10,  9,  8,  7,  6,  5,  4])

In [ ]:
np.linspace?

In [ ]:
np.arange?

In [134]:
np.linspace(1, 2, 2)

array([1., 2.])

In [135]:
np.random

<module 'numpy.random' from 'C:\\ProgramData\\Anaconda3\\envs\\tools-and-techniques-in-data-science\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [137]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method


In [ ]:
np.random.random((1, 2))

In [ ]:
np.random.rand?

In [ ]:
dir(np.random)

In [171]:
np.random.randint(1, 10, (2, 2))

array([[2, 9],
       [3, 4]])

In [ ]:
np.array([]).flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [21]:
arr = np.array([1])

print('arr: ', arr)
print('ndim: ', arr.ndim)
print('shape: ', arr.shape)
print('size: ', arr.size)
print('itemsize: ', arr.itemsize)
print('dtype: ', arr.dtype)
print('nbytes: ', arr.nbytes)
print('strides: ', arr.strides)

arr:  [1]
ndim:  1
shape:  (1,)
size:  1
itemsize:  4
dtype:  int32
nbytes:  4
strides:  (4,)


In [1]:
import numpy as np

In [ ]:
np.array?

In [ ]:
np.empty?

In [ ]:
np.arange?

In [ ]:
np.linspace?

In [6]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method


In [ ]:
np.random.random?

In [ ]:
np.random.rand?

In [ ]:
np.random.randint(9)

In [ ]:
np.zeros_like?