In [2]:
import numpy as np

In [3]:
arr = np.random.randint(10, size=4)
print(arr + 2)
print(arr - 2)
print(arr * 2)
print(arr / 2)
print(arr // 2)

[5 5 8 6]
[1 1 4 2]
[ 6  6 12  8]
[1.5 1.5 3.  2. ]
[1 1 3 2]


In [21]:
arr = np.random.randint(10, size=4)
print(np.add(arr, 2))
print(np.subtract(arr, 2))

[4 4 6 5]
[0 0 2 1]


In [22]:
np.array([1, 2]) - np.array([3, 4])

array([-2, -2])

In [23]:
np.array([1, 2]) - np.array([[1], [2]])

array([[ 0,  1],
       [-1,  0]])

In [24]:
np.array([1,2,3]) - np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
np.cbrt?

In [ ]:
np.sqrt?

In [ ]:
np.log?

In [34]:
np.cumsum(np.array([[1, 2, 3], [4, 5, 6]]), axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)

In [35]:
np.isnan(np.array([1, 2, 3]))

array([False, False, False])

In [41]:
np.prod([[1, 2, 3, 4], [5, 6, 7, 8]], axis=0)

array([ 5, 12, 21, 32])

In [42]:
np.max

<function numpy.amax(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [45]:
np.sum([1, 2, 3, 4, 5])

15

In [47]:
np.sum([[1, 2, 3], [4, 5, 6]], axis=0)

array([5, 7, 9])

In [48]:
np.mean

<function numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>, *, where=<no value>)>

In [49]:
np.average

<function numpy.average(a, axis=None, weights=None, returned=False)>

In [50]:
np.var

<function numpy.var(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)>

In [53]:
np.std

<function numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<no value>, *, where=<no value>)>

In [54]:
np.percentile

<function numpy.percentile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)>

In [55]:
np.array([1, 2, 3]) > np.array([1, 1, 1])

array([False,  True,  True])

In [57]:
np.array([[1, 2]]) > np.array([[1, 1]])

array([[False,  True]])

In [58]:
np.array([[1, 2]]) > np.array([[1, 1, 2]])

ValueError: operands could not be broadcast together with shapes (1,2) (1,3) 

In [64]:
arr = np.array([1, 2, 3, 4])
np.where(arr % 2 == 0, 'even', 'odd')

array(['odd', 'even', 'odd', 'even'], dtype='<U4')

In [65]:
arr % 2 == 0

array([False,  True, False,  True])

In [9]:
np.divide(np.array([1, 2, 3]), 3)

array([0.33333333, 0.66666667, 1.        ])

In [10]:
np.array([1, 2, 3]) > np.array([1, -1, 0])

array([False,  True,  True])

In [ ]:
np.where?

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.where(arr>5, 1, 0)

array([0, 0, 0, 0, 0, 1, 1, 1, 1])

In [19]:
np.where(arr>5)

(array([5, 6, 7, 8], dtype=int64),)

In [25]:
np.where(arr>5, arr, arr*10)

array([10, 20, 30, 40, 50,  6,  7,  8,  9])