In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [10]:
arr2 = arr[2:4]
arr2

array([3, 4])

In [11]:
arr2[0] = 99

In [12]:
arr, arr2

(array([ 1,  2, 99,  4,  5,  6]), array([99,  4]))

In [5]:
id(arr), id(arr2)

(1489677645648, 1489656078224)

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr2 = arr[2:4]
arr2

array([2, 3])

In [21]:
arr.strides, arr2.strides

((4,), (8,))

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr2 = arr[2:7:2]
arr2

array([2, 4, 6])

In [23]:
arr.strides, arr2.strides

((4,), (8,))

In [27]:
arr.dtype, arr2.dtype

(dtype('int32'), dtype('int32'))

In [31]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr2 = arr[7:2:-1]
arr2

array([7, 6, 5, 4, 3])

In [32]:
arr.strides, arr2.strides

((4,), (-4,))

In [33]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr2 = arr[200:700]
arr2

array([], dtype=int32)

In [34]:
arr.strides, arr2.strides

((4,), (4,))