In [1]:
import numpy as np

In [31]:
arr = np.arange(10)
print(arr)
print(arr.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [32]:
arr.shape = (2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
arr.shape = (10, 1)
arr

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [34]:
arr.data, arr2.data

(<memory at 0x000002D3DCE28A00>, <memory at 0x000002D3DCE28AD0>)

In [35]:
arr = np.arange(10)
arr2 = arr
arr.data, arr2.data

(<memory at 0x000002D3DCE32640>, <memory at 0x000002D3DCE32700>)

In [17]:
arr = np.arange(10)
arr2 = arr

In [18]:
arr2.shape = (2, 5)

In [16]:
arr.shape, arr2.shape

((2, 5), (2, 5))

In [19]:
arr = np.arange(10)
arr2 = arr[:]

In [20]:
arr2.shape = (2, 5)

In [21]:
arr.shape, arr2.shape

((10,), (2, 5))

In [22]:
arr = np.arange(10)
arr2 = np.reshape(arr, (2, 5))

In [23]:
arr.shape, arr2.shape

((10,), (2, 5))

In [24]:
arr.data, arr2.data

(<memory at 0x000002D3DB933280>, <memory at 0x000002D3DCE28930>)

In [25]:
arr[4] = 99

In [26]:
arr, arr2

(array([ 0,  1,  2,  3, 99,  5,  6,  7,  8,  9]),
 array([[ 0,  1,  2,  3, 99],
        [ 5,  6,  7,  8,  9]]))

In [30]:
np.ndarray.data?

Type:        getset_descriptor
String form: <attribute 'data' of 'numpy.ndarray' objects>
Docstring:   Python buffer object pointing to the start of the array's data.


In [46]:
arr = np.arange(10)
arr2 = np.resize(arr, (2, 5))

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [52]:
arr = np.arange(10)
np.resize(arr, 4)

array([0, 1, 2, 3])

In [54]:
np.resize(arr, 20)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.resize(arr, (4,4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 1],
       [2, 3, 4, 5]])

In [60]:
arr = np.arange(10)
arr.transpose()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
arr2 = arr.transpose()
arr2

array([[ 1,  5],
       [ 2, 99],
       [ 3,  7],
       [ 4,  8]])

In [69]:
arr.shape, arr2.shape

((2, 4), (4, 2))

In [70]:
arr[1,1]=99
arr

array([[ 1,  2,  3,  4],
       [ 5, 99,  7,  8]])

In [71]:
arr2

array([[ 1,  5],
       [ 2, 99],
       [ 3,  7],
       [ 4,  8]])

In [ ]:
np.swapaxes?

In [82]:
arr = np.array([[1], [2]])
arr2 = arr.flatten()

In [83]:
arr.shape, arr2.shape

((2, 1), (2,))

In [84]:
arr[0,0] = 99
arr

array([[99],
       [ 2]])

In [85]:
arr2

array([1, 2])

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
arr.shape = 6

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [10]:
arr = np.arange(9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
arr2 = np.reshape(arr, (3, 3))
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
id(arr) == id(arr2)

False

In [13]:
arr[0] = 99
arr

array([99,  1,  2,  3,  4,  5,  6,  7,  8])

In [14]:
arr2

array([[99,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [15]:
arr.data, arr2.data

(<memory at 0x00000202EAFCA700>, <memory at 0x00000202EAFC2930>)

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5 ,6 ,7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.resize(arr, (1,9))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [34]:
np.transpose([[1, 2, 3, 4, 5]])

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [37]:
np.array([[1, 2, 3, 4, 5]]).T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
np.array([[1, 2, 3, 4, 5]]).T

In [32]:
np.transpose(([[1, 2]]))

array([[1],
       [2]])

In [33]:
np.array([[1, 2]]).T

array([[1],
       [2]])

In [ ]:
np.ndarray.flatten?

In [53]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [54]:
arr.flatten('C')

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
arr.flatten('F')

array([0, 3, 6, 1, 4, 7, 2, 5, 8])

In [56]:
arr = np.arange(9).reshape((3, 3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr2 = arr.flatten()

In [60]:
arr[0, 0] = 99
arr

array([[99,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [61]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])