In [1]:
import numpy as np

In [5]:
np.append([1, 2, 3, 4, 5], 1)

array([1, 2, 3, 4, 5, 1])

In [6]:
np.append([[1, 2, 3], [4,5,6]], 4)

array([1, 2, 3, 4, 5, 6, 4])

In [13]:
np.append([[1, 2, 3], [4,5,6]], [[[9, 9, 9]]])

array([1, 2, 3, 4, 5, 6, 9, 9, 9])

In [39]:
np.append([[1, 2, 3], [4,5,6]], [[9, 9, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [9, 9, 9]])

In [33]:
np.append([[1, 2, 3], [4,5,6]], [[9], [9]], axis=1)

array([[1, 2, 3, 9],
       [4, 5, 6, 9]])

In [20]:
np.insert([1, 2, 3, 4, 5, 6, 7, 8, 9], 4, 99)

array([ 1,  2,  3,  4, 99,  5,  6,  7,  8,  9])

In [21]:
np.insert([1, 2, 3, 4, 5, 6, 7, 8, 9], 4, [99, 99, 99])

array([ 1,  2,  3,  4, 99, 99, 99,  5,  6,  7,  8,  9])

In [24]:
np.insert([[1, 2, 3], [4,5,6]], 4, 99)

array([ 1,  2,  3,  4, 99,  5,  6])

In [28]:
np.insert([[1, 2, 3], [4,5,6]], 1, 99, axis=0)

array([[ 1,  2,  3],
       [99, 99, 99],
       [ 4,  5,  6]])

In [29]:
np.insert([[1, 2, 3], [4,5,6]], 1, 99, axis=1)

array([[ 1, 99,  2,  3],
       [ 4, 99,  5,  6]])

In [37]:
np.insert([[1, 2, 3], [4,5,6]], 1, [[99]], axis=0)

array([[ 1,  2,  3],
       [99, 99, 99],
       [ 4,  5,  6]])

In [1]:
import numpy as np