In [2]:
import numpy as np

In [ ]:
np.concatenate?

In [5]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.concatenate((arr1, arr2), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.concatenate((arr1, arr2), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [9]:
arr1 = np.array([[1,2],
                [3,4]])
arr2 = np.array([[5,6],
                [7,8]])

np.concatenate((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [13]:
arr1 = np.array([[1,2],
                [3,4],
                [9,9]])
arr2 = np.array([[5,6],
                [7,8]])

np.concatenate((arr1, arr2))

array([[1, 2],
       [3, 4],
       [9, 9],
       [5, 6],
       [7, 8]])

In [14]:
arr1 = np.array([[1,2,9],
                [3,4,9]])
arr2 = np.array([[5,6],
                [7,8]])

np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 9, 5, 6],
       [3, 4, 9, 7, 8]])

In [19]:
arr1 = np.array([
                  [[1,2],
                  [3,4]],

                  [[5,6],
                  [7,8]]
                ])
arr2 = np.array([
                  [[9,9],
                  [9,9]]
                ])

np.concatenate((arr1, arr2), axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 9],
        [9, 9]]])

In [18]:
arr1.shape, arr2.shape

((2, 2, 2), (1, 2, 2))

In [ ]:
np.row_stack?

In [ ]:
np.column_stack?

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.row_stack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.column_stack((arr1, arr2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))

print(arr1, '\n\n', arr2)

[[7 6]
 [6 9]] 

 [[9 8]
 [3 6]]


In [122]:
np.row_stack((arr1, arr2))

array([[7, 6],
       [6, 9],
       [9, 8],
       [3, 6]])

In [123]:
np.column_stack((arr1, arr2))

array([[7, 6, 9, 8],
       [6, 9, 3, 6]])

In [ ]:
np.hstack?

In [ ]:
np.vstack?

In [127]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6,6])

np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6, 6])

In [31]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,3))

print(arr1, '\n\n', arr2)

[[0 6]
 [8 0]] 

 [[3 5 0]
 [1 9 1]]


In [117]:
np.hstack((arr1, arr2))

array([[0, 6, 3, 5, 0],
       [8, 0, 1, 9, 1]])

In [128]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (3,2))

print(arr1, '\n\n', arr2)

[[1 8]
 [0 8]] 

 [[2 0]
 [7 9]
 [9 0]]


In [129]:
np.vstack((arr1, arr2))

array([[1, 8],
       [0, 8],
       [2, 0],
       [7, 9],
       [9, 0]])

In [ ]:
np.stack?

In [177]:
arr1 = np.random.randint(0, 10, 4)
arr2 = np.random.randint(0, 10, 4)

print(arr1, '\n\n', arr2)

[6 5 0 0] 

 [7 3 7 1]


In [178]:
np.stack((arr1, arr2), axis=0)

array([[6, 5, 0, 0],
       [7, 3, 7, 1]])

In [179]:
np.stack((arr1, arr2), axis=1)

array([[6, 7],
       [5, 3],
       [0, 7],
       [0, 1]])

In [180]:
np.stack((arr1, arr2), axis=-1)

array([[6, 7],
       [5, 3],
       [0, 7],
       [0, 1]])

In [165]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))

print(arr1, '\n\n', arr2)

[[2 7]
 [0 0]] 

 [[6 9]
 [8 2]]


In [166]:
np.stack((arr1, arr2))

array([[[2, 7],
        [0, 0]],

       [[6, 9],
        [8, 2]]])

In [174]:
np.stack((arr1, arr2), axis=1)

array([[[2, 7],
        [6, 9]],

       [[0, 0],
        [8, 2]]])

In [175]:
np.stack((arr1, arr2), axis=2)

array([[[2, 6],
        [7, 9]],

       [[0, 8],
        [0, 2]]])

In [176]:
np.stack((arr1, arr2), axis=-1)

array([[[2, 6],
        [7, 9]],

       [[0, 8],
        [0, 2]]])

In [ ]:
np.dstack?

In [184]:
arr1 = np.random.randint(0, 10, 4)
arr2 = np.random.randint(0, 10, 4)

print(arr1, '\n\n', arr2)

[2 4 3 0] 

 [1 6 4 2]


In [185]:
np.dstack((arr1, arr2))

array([[[2, 1],
        [4, 6],
        [3, 4],
        [0, 2]]])

In [191]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))

print(arr1, '\n\n', arr2)

[[3 6]
 [9 3]] 

 [[9 1]
 [4 4]]


In [187]:
np.dstack((arr1, arr2))

array([[[1, 4],
        [2, 1]],

       [[0, 0],
        [3, 6]]])

In [188]:
arr1 = np.random.randint(0, 10, (2,2,2))
arr2 = np.random.randint(0, 10, (2,2,2))

print(arr1, '\n\n', arr2)

[[[4 8]
  [0 1]]

 [[6 2]
  [5 1]]] 

 [[[2 1]
  [3 6]]

 [[0 2]
  [9 9]]]


In [189]:
np.dstack((arr1, arr2))

array([[[4, 8, 2, 1],
        [0, 1, 3, 6]],

       [[6, 2, 0, 2],
        [5, 1, 9, 9]]])

In [194]:
arr = np.random.randint(0, 10, 10)
arr

array([1, 9, 6, 4, 4, 0, 9, 9, 6, 0])

In [195]:
np.split(arr, 2)

[array([1, 9, 6, 4, 4]), array([0, 9, 9, 6, 0])]

In [ ]:
np.split(arr, 3)

In [197]:
np.split(arr, 5)

[array([1, 9]), array([6, 4]), array([4, 0]), array([9, 9]), array([6, 0])]

In [201]:
np.array_split(arr, 4)

[array([1, 9, 6]), array([4, 4, 0]), array([9, 9]), array([6, 0])]

In [ ]:
np.array_split?

In [204]:
arr = np.random.randint(0, 10, (6,6))
arr

array([[4, 2, 0, 1, 2, 4],
       [7, 5, 7, 4, 5, 2],
       [6, 2, 6, 8, 9, 3],
       [4, 8, 6, 5, 8, 2],
       [4, 6, 2, 9, 4, 7],
       [6, 6, 5, 7, 8, 9]])

In [209]:
np.split(arr, 2, axis=1)

[array([[4, 2, 0],
        [7, 5, 7],
        [6, 2, 6],
        [4, 8, 6],
        [4, 6, 2],
        [6, 6, 5]]),
 array([[1, 2, 4],
        [4, 5, 2],
        [8, 9, 3],
        [5, 8, 2],
        [9, 4, 7],
        [7, 8, 9]])]

In [211]:
np.array_split(arr, 4, axis=1)

[array([[4, 2],
        [7, 5],
        [6, 2],
        [4, 8],
        [4, 6],
        [6, 6]]),
 array([[0, 1],
        [7, 4],
        [6, 8],
        [6, 5],
        [2, 9],
        [5, 7]]),
 array([[2],
        [5],
        [9],
        [8],
        [4],
        [8]]),
 array([[4],
        [2],
        [3],
        [2],
        [7],
        [9]])]

In [ ]:
np.hsplit?

In [ ]:
np.vsplit?

In [214]:
arr = np.random.randint(0,10,10)

In [217]:
np.hsplit(arr, 2)

[array([5, 9, 1, 7, 3]), array([8, 4, 2, 0, 5])]

In [218]:
np.hsplit(arr, 3)

ValueError: array split does not result in an equal division

In [223]:
arr = np.random.randint(0,10,(6,6))
arr

array([[6, 6, 4, 0, 1, 3],
       [1, 4, 0, 8, 6, 5],
       [1, 4, 2, 7, 0, 4],
       [5, 4, 3, 0, 0, 6],
       [9, 5, 0, 8, 2, 2],
       [1, 2, 9, 0, 3, 8]])

In [224]:
np.hsplit(arr, 2)

[array([[6, 6, 4],
        [1, 4, 0],
        [1, 4, 2],
        [5, 4, 3],
        [9, 5, 0],
        [1, 2, 9]]),
 array([[0, 1, 3],
        [8, 6, 5],
        [7, 0, 4],
        [0, 0, 6],
        [8, 2, 2],
        [0, 3, 8]])]

In [225]:
arr = np.random.randint(0,10,(6,6))
arr

array([[0, 9, 1, 4, 3, 1],
       [0, 5, 9, 5, 9, 0],
       [2, 7, 3, 0, 3, 9],
       [4, 7, 7, 0, 9, 7],
       [1, 3, 9, 4, 0, 0],
       [6, 2, 6, 6, 6, 9]])

In [226]:
np.vsplit(arr, 2)

[array([[0, 9, 1, 4, 3, 1],
        [0, 5, 9, 5, 9, 0],
        [2, 7, 3, 0, 3, 9]]),
 array([[4, 7, 7, 0, 9, 7],
        [1, 3, 9, 4, 0, 0],
        [6, 2, 6, 6, 6, 9]])]

In [228]:
arr = np.array([1])
np.array_split(arr, 5)

[array([1]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))

arr1, arr2

(array([[3, 7],
        [0, 8]]),
 array([[1, 4],
        [3, 9]]))

In [10]:
np.concatenate((arr1, arr2), axis=1)

array([[3, 7, 1, 4],
       [0, 8, 3, 9]])

In [11]:
np.vstack((arr1, arr2))

array([[3, 7],
       [0, 8],
       [1, 4],
       [3, 9]])

In [13]:
np.hstack((arr1, arr2))

array([[3, 7, 1, 4],
       [0, 8, 3, 9]])

In [21]:
np.stack((arr1, arr2), axis=1)

array([[[3, 7],
        [1, 4]],

       [[0, 8],
        [3, 9]]])

In [83]:
arr1 = np.random.randint(0,9, (2,2,2))
arr2 = np.random.randint(0,9, (2,2,2))
arr1, arr2

(array([[[0, 1],
         [8, 5]],
 
        [[4, 1],
         [0, 0]]]),
 array([[[2, 2],
         [5, 6]],
 
        [[4, 4],
         [7, 8]]]))

In [85]:
np.concatenate((arr1,arr2),axis=1)

array([[[0, 1],
        [8, 5],
        [2, 2],
        [5, 6]],

       [[4, 1],
        [0, 0],
        [4, 4],
        [7, 8]]])

In [78]:
arr1 = [1,2,3]
arr2 = [4,5,6]

In [79]:
np.column_stack((arr1,arr2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [81]:
np.stack((arr1,arr2), axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
arr1 = np.random.randint(0, 10, (4,4))
arr2 = np.random.randint(0, 10, (4,4))

arr1, arr2

(array([[9, 8, 7, 7],
        [2, 9, 0, 9],
        [3, 1, 8, 7],
        [7, 6, 6, 3]]),
 array([[1, 2, 6, 0],
        [8, 3, 3, 4],
        [9, 7, 3, 8],
        [5, 0, 7, 4]]))

In [96]:
np.vsplit(arr1,2)

[array([[9, 8, 7, 7],
        [2, 9, 0, 9]]),
 array([[3, 1, 8, 7],
        [7, 6, 6, 3]])]

In [97]:
np.hsplit(arr1,2)

[array([[9, 8],
        [2, 9],
        [3, 1],
        [7, 6]]),
 array([[7, 7],
        [0, 9],
        [8, 7],
        [6, 3]])]

In [105]:
np.split(arr1,2,axis=1)

[array([[9, 8],
        [2, 9],
        [3, 1],
        [7, 6]]),
 array([[7, 7],
        [0, 9],
        [8, 7],
        [6, 3]])]

In [103]:
np.split?

Signature: np.split(ary, indices_or_sections, axis=0)
Docstring:
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned correspondingly.
axis : int, optional
    The axis along which to split, default is 0.

Returns
-------
sub-arrays : list of ndarrays
    A list of sub-arrays as views into `ary`.

Raises
------
ValueError
    If `indices_or_sections` is given as

In [ ]:
np.stack?

In [ ]:
np.vstack?

In [ ]:
np.hstack?

In [ ]:
np.column_stack?

In [ ]:
np.row_stack?

In [125]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))
arr1, arr2

(array([[3, 3, 7],
        [3, 5, 8],
        [3, 7, 7]]),
 array([[6, 2, 8],
        [0, 6, 8],
        [4, 7, 4]]))

In [126]:
np.hstack((arr1,arr2))

array([[3, 3, 7, 6, 2, 8],
       [3, 5, 8, 0, 6, 8],
       [3, 7, 7, 4, 7, 4]])

In [127]:
np.vstack((arr1,arr2))

array([[3, 3, 7],
       [3, 5, 8],
       [3, 7, 7],
       [6, 2, 8],
       [0, 6, 8],
       [4, 7, 4]])

In [128]:
np.row_stack((arr1,arr2))

array([[3, 3, 7],
       [3, 5, 8],
       [3, 7, 7],
       [6, 2, 8],
       [0, 6, 8],
       [4, 7, 4]])

In [129]:
np.column_stack((arr1, arr2))

array([[3, 3, 7, 6, 2, 8],
       [3, 5, 8, 0, 6, 8],
       [3, 7, 7, 4, 7, 4]])

In [158]:
arr1 = np.random.randint(1,10,4)
arr2 = np.random.randint(1,10,4)
arr1,arr2

(array([3, 4, 4, 6]), array([2, 2, 7, 8]))

In [159]:
np.hstack((arr1,arr2))

array([3, 4, 4, 6, 2, 2, 7, 8])

In [160]:
np.vstack((arr1,arr2))

array([[3, 4, 4, 6],
       [2, 2, 7, 8]])

In [136]:
np.stack((arr1,arr2))

array([[6, 6, 7, 6],
       [6, 4, 3, 7]])

In [137]:
np.stack((arr1,arr2), axis=1)

array([[6, 6],
       [6, 4],
       [7, 3],
       [6, 7]])

In [145]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))
arr1, arr2

(array([[1, 5, 8],
        [7, 9, 6],
        [5, 5, 1]]),
 array([[5, 3, 4],
        [8, 5, 0],
        [0, 5, 4]]))

In [146]:
np.stack((arr1,arr2))

array([[[1, 5, 8],
        [7, 9, 6],
        [5, 5, 1]],

       [[5, 3, 4],
        [8, 5, 0],
        [0, 5, 4]]])

In [149]:
np.stack((arr1,arr2), axis=1)

array([[[1, 5, 8],
        [5, 3, 4]],

       [[7, 9, 6],
        [8, 5, 0]],

       [[5, 5, 1],
        [0, 5, 4]]])

In [120]:
arr1 = [1,2,3]
arr2 = [4,5,6]

In [121]:
np.row_stack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
np.column_stack((arr1,arr2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
np.concatenate?

In [152]:
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(0,10,(3,3))
arr1, arr2

(array([[6, 2, 1],
        [5, 6, 5],
        [5, 7, 9]]),
 array([[8, 1, 1],
        [1, 8, 4],
        [8, 8, 8]]))

In [154]:
np.concatenate((arr1,arr2))

array([[6, 2, 1],
       [5, 6, 5],
       [5, 7, 9],
       [8, 1, 1],
       [1, 8, 4],
       [8, 8, 8]])

In [155]:
np.concatenate((arr1,arr2),axis=1)

array([[6, 2, 1, 8, 1, 1],
       [5, 6, 5, 1, 8, 4],
       [5, 7, 9, 8, 8, 8]])

In [157]:
arr1 = np.random.randint(1,10,4)
arr2 = np.random.randint(1,10,4)
arr1,arr2

(array([6, 8, 5, 3]), array([3, 7, 3, 2]))

In [163]:
np.concatenate((arr1,arr2))

array([3, 4, 4, 6, 2, 2, 7, 8])

In [164]:
np.concatenate((arr1,arr2),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [176]:
np.hstack(([1,2],[3,4]))

array([1, 2, 3, 4])

In [ ]:
np.split?

In [ ]:
np.vsplit?

In [ ]:
np.hsplit?

In [181]:
arr = np.random.randint(0,10,(4,4))
arr

array([[9, 8, 1, 9],
       [8, 4, 9, 4],
       [7, 6, 2, 8],
       [7, 2, 7, 7]])

In [182]:
np.split(arr,2)

[array([[9, 8, 1, 9],
        [8, 4, 9, 4]]),
 array([[7, 6, 2, 8],
        [7, 2, 7, 7]])]

In [183]:
np.split(arr,2,axis=1)

[array([[9, 8],
        [8, 4],
        [7, 6],
        [7, 2]]),
 array([[1, 9],
        [9, 4],
        [2, 8],
        [7, 7]])]

In [185]:
np.hsplit(arr,2)

[array([[9, 8],
        [8, 4],
        [7, 6],
        [7, 2]]),
 array([[1, 9],
        [9, 4],
        [2, 8],
        [7, 7]])]

In [186]:
np.vsplit(arr,2)

[array([[9, 8, 1, 9],
        [8, 4, 9, 4]]),
 array([[7, 6, 2, 8],
        [7, 2, 7, 7]])]

In [ ]:
np.array_split?

In [195]:
np.array_split([1,2,3,4,5,6],4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [197]:
arr = np.random.randint(1,5,(3,3))
arr

array([[3, 2, 2],
       [1, 1, 3],
       [1, 2, 3]])

In [199]:
np.array_split(arr,2,axis=1)

[array([[3, 2],
        [1, 1],
        [1, 2]]),
 array([[2],
        [3],
        [3]])]