In [2]:
import numpy as np

In [ ]:
np.concatenate?

In [5]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.concatenate((arr1, arr2), axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.concatenate((arr1, arr2), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [9]:
arr1 = np.array([[1,2],
                [3,4]])
arr2 = np.array([[5,6],
                [7,8]])

np.concatenate((arr1, arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [13]:
arr1 = np.array([[1,2],
                [3,4],
                [9,9]])
arr2 = np.array([[5,6],
                [7,8]])

np.concatenate((arr1, arr2))

array([[1, 2],
       [3, 4],
       [9, 9],
       [5, 6],
       [7, 8]])

In [14]:
arr1 = np.array([[1,2,9],
                [3,4,9]])
arr2 = np.array([[5,6],
                [7,8]])

np.concatenate((arr1, arr2), axis=1)

array([[1, 2, 9, 5, 6],
       [3, 4, 9, 7, 8]])

In [19]:
arr1 = np.array([
                  [[1,2],
                  [3,4]],

                  [[5,6],
                  [7,8]]
                ])
arr2 = np.array([
                  [[9,9],
                  [9,9]]
                ])

np.concatenate((arr1, arr2), axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 9],
        [9, 9]]])

In [18]:
arr1.shape, arr2.shape

((2, 2, 2), (1, 2, 2))

In [ ]:
np.row_stack?

In [ ]:
np.column_stack?

In [24]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.row_stack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

np.column_stack((arr1, arr2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))

print(arr1, '\n\n', arr2)

[[7 6]
 [6 9]] 

 [[9 8]
 [3 6]]


In [122]:
np.row_stack((arr1, arr2))

array([[7, 6],
       [6, 9],
       [9, 8],
       [3, 6]])

In [123]:
np.column_stack((arr1, arr2))

array([[7, 6, 9, 8],
       [6, 9, 3, 6]])

In [ ]:
np.hstack?

In [ ]:
np.vstack?

In [127]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6,6])

np.hstack((arr1, arr2))

array([1, 2, 3, 4, 5, 6, 6])

In [31]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,3))

print(arr1, '\n\n', arr2)

[[0 6]
 [8 0]] 

 [[3 5 0]
 [1 9 1]]


In [117]:
np.hstack((arr1, arr2))

array([[0, 6, 3, 5, 0],
       [8, 0, 1, 9, 1]])

In [128]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (3,2))

print(arr1, '\n\n', arr2)

[[1 8]
 [0 8]] 

 [[2 0]
 [7 9]
 [9 0]]


In [129]:
np.vstack((arr1, arr2))

array([[1, 8],
       [0, 8],
       [2, 0],
       [7, 9],
       [9, 0]])

In [ ]:
np.stack?

In [177]:
arr1 = np.random.randint(0, 10, 4)
arr2 = np.random.randint(0, 10, 4)

print(arr1, '\n\n', arr2)

[6 5 0 0] 

 [7 3 7 1]


In [178]:
np.stack((arr1, arr2), axis=0)

array([[6, 5, 0, 0],
       [7, 3, 7, 1]])

In [179]:
np.stack((arr1, arr2), axis=1)

array([[6, 7],
       [5, 3],
       [0, 7],
       [0, 1]])

In [180]:
np.stack((arr1, arr2), axis=-1)

array([[6, 7],
       [5, 3],
       [0, 7],
       [0, 1]])

In [165]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))

print(arr1, '\n\n', arr2)

[[2 7]
 [0 0]] 

 [[6 9]
 [8 2]]


In [166]:
np.stack((arr1, arr2))

array([[[2, 7],
        [0, 0]],

       [[6, 9],
        [8, 2]]])

In [174]:
np.stack((arr1, arr2), axis=1)

array([[[2, 7],
        [6, 9]],

       [[0, 0],
        [8, 2]]])

In [175]:
np.stack((arr1, arr2), axis=2)

array([[[2, 6],
        [7, 9]],

       [[0, 8],
        [0, 2]]])

In [176]:
np.stack((arr1, arr2), axis=-1)

array([[[2, 6],
        [7, 9]],

       [[0, 8],
        [0, 2]]])

In [ ]:
np.dstack?

In [184]:
arr1 = np.random.randint(0, 10, 4)
arr2 = np.random.randint(0, 10, 4)

print(arr1, '\n\n', arr2)

[2 4 3 0] 

 [1 6 4 2]


In [185]:
np.dstack((arr1, arr2))

array([[[2, 1],
        [4, 6],
        [3, 4],
        [0, 2]]])

In [191]:
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))

print(arr1, '\n\n', arr2)

[[3 6]
 [9 3]] 

 [[9 1]
 [4 4]]


In [187]:
np.dstack((arr1, arr2))

array([[[1, 4],
        [2, 1]],

       [[0, 0],
        [3, 6]]])

In [188]:
arr1 = np.random.randint(0, 10, (2,2,2))
arr2 = np.random.randint(0, 10, (2,2,2))

print(arr1, '\n\n', arr2)

[[[4 8]
  [0 1]]

 [[6 2]
  [5 1]]] 

 [[[2 1]
  [3 6]]

 [[0 2]
  [9 9]]]


In [189]:
np.dstack((arr1, arr2))

array([[[4, 8, 2, 1],
        [0, 1, 3, 6]],

       [[6, 2, 0, 2],
        [5, 1, 9, 9]]])

In [194]:
arr = np.random.randint(0, 10, 10)
arr

array([1, 9, 6, 4, 4, 0, 9, 9, 6, 0])

In [195]:
np.split(arr, 2)

[array([1, 9, 6, 4, 4]), array([0, 9, 9, 6, 0])]

In [ ]:
np.split(arr, 3)

In [197]:
np.split(arr, 5)

[array([1, 9]), array([6, 4]), array([4, 0]), array([9, 9]), array([6, 0])]

In [201]:
np.array_split(arr, 4)

[array([1, 9, 6]), array([4, 4, 0]), array([9, 9]), array([6, 0])]

In [ ]:
np.array_split?

In [204]:
arr = np.random.randint(0, 10, (6,6))
arr

array([[4, 2, 0, 1, 2, 4],
       [7, 5, 7, 4, 5, 2],
       [6, 2, 6, 8, 9, 3],
       [4, 8, 6, 5, 8, 2],
       [4, 6, 2, 9, 4, 7],
       [6, 6, 5, 7, 8, 9]])

In [209]:
np.split(arr, 2, axis=1)

[array([[4, 2, 0],
        [7, 5, 7],
        [6, 2, 6],
        [4, 8, 6],
        [4, 6, 2],
        [6, 6, 5]]),
 array([[1, 2, 4],
        [4, 5, 2],
        [8, 9, 3],
        [5, 8, 2],
        [9, 4, 7],
        [7, 8, 9]])]

In [211]:
np.array_split(arr, 4, axis=1)

[array([[4, 2],
        [7, 5],
        [6, 2],
        [4, 8],
        [4, 6],
        [6, 6]]),
 array([[0, 1],
        [7, 4],
        [6, 8],
        [6, 5],
        [2, 9],
        [5, 7]]),
 array([[2],
        [5],
        [9],
        [8],
        [4],
        [8]]),
 array([[4],
        [2],
        [3],
        [2],
        [7],
        [9]])]

In [ ]:
np.hsplit?

In [ ]:
np.vsplit?

In [214]:
arr = np.random.randint(0,10,10)

In [217]:
np.hsplit(arr, 2)

[array([5, 9, 1, 7, 3]), array([8, 4, 2, 0, 5])]

In [218]:
np.hsplit(arr, 3)

ValueError: array split does not result in an equal division

In [223]:
arr = np.random.randint(0,10,(6,6))
arr

array([[6, 6, 4, 0, 1, 3],
       [1, 4, 0, 8, 6, 5],
       [1, 4, 2, 7, 0, 4],
       [5, 4, 3, 0, 0, 6],
       [9, 5, 0, 8, 2, 2],
       [1, 2, 9, 0, 3, 8]])

In [224]:
np.hsplit(arr, 2)

[array([[6, 6, 4],
        [1, 4, 0],
        [1, 4, 2],
        [5, 4, 3],
        [9, 5, 0],
        [1, 2, 9]]),
 array([[0, 1, 3],
        [8, 6, 5],
        [7, 0, 4],
        [0, 0, 6],
        [8, 2, 2],
        [0, 3, 8]])]

In [225]:
arr = np.random.randint(0,10,(6,6))
arr

array([[0, 9, 1, 4, 3, 1],
       [0, 5, 9, 5, 9, 0],
       [2, 7, 3, 0, 3, 9],
       [4, 7, 7, 0, 9, 7],
       [1, 3, 9, 4, 0, 0],
       [6, 2, 6, 6, 6, 9]])

In [226]:
np.vsplit(arr, 2)

[array([[0, 9, 1, 4, 3, 1],
        [0, 5, 9, 5, 9, 0],
        [2, 7, 3, 0, 3, 9]]),
 array([[4, 7, 7, 0, 9, 7],
        [1, 3, 9, 4, 0, 0],
        [6, 2, 6, 6, 6, 9]])]

In [228]:
arr = np.array([1])
np.array_split(arr, 5)

[array([1]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]