In [1]:
import numpy as np

In [ ]:
np.loadtxt?

In [ ]:
np.genfromtxt?

In [4]:
!cat datasets/data0.txt

3 9  12 22  45  91  33  61 12  19  62 29  64  31


In [5]:
np.loadtxt('datasets/data0.txt')

array([ 3.,  9., 12., 22., 45., 91., 33., 61., 12., 19., 62., 29., 64.,
       31.])

In [10]:
np.genfromtxt('datasets/data0.txt')

array([ 3.,  9., 12., 22., 45., 91., 33., 61., 12., 19., 62., 29., 64.,
       31.])

In [7]:
!cat datasets/data1.txt

12  19  62
9   33  61
22  45  91 
29  64  31


In [11]:
np.loadtxt('datasets/data1.txt')

array([[12., 19., 62.],
       [ 9., 33., 61.],
       [22., 45., 91.],
       [29., 64., 31.]])

In [12]:
np.genfromtxt('datasets/data1.txt')

array([[12., 19., 62.],
       [ 9., 33., 61.],
       [22., 45., 91.],
       [29., 64., 31.]])